services:
  grafana:
    user: root
    container_name: 'testorg-image-panel'

    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.2.2}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/testorg-image-panel
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/testorg-image-panel

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.testorg-image-panel:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: testorg-image-panel
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/grafana/provisioning/dashboards/home.json
      GF_INSTALL_PLUGINS: marcusolsson-static-datasource
